version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx:/etc/nginx/conf.d
      - /home/ubuntu/prj/khukie-air/khukieair_front/public:/src/www/static
    depends_on:
      - web.api
      - web.front

  web.api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn khukieAir.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"

  web.front:
    build: './khukieair_front'
    ports:
      - "8080:80"