# Generated by Django 3.0.7 on 2020-06-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('trash_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_path', models.TextField()),
                ('type', models.CharField(max_length=6)),
                ('trashed_at', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.DateTimeField(default=None, null=True)),
                ('content_created_at', models.DateTimeField(default=None, null=True)),
                ('content_modified_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('size', models.PositiveIntegerField()),
                ('obj_name', models.CharField(max_length=256)),
                ('cascade_trash', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='S3App.Trash')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('path', models.TextField()),
                ('size', models.PositiveIntegerField(default=0)),
                ('folder_name', models.CharField(max_length=255)),
                ('parent_folder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='S3App.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_created_at', models.DateTimeField()),
                ('content_modified_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('path', models.TextField()),
                ('size', models.PositiveIntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('parent_folder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='S3App.Folder')),
            ],
        ),
    ]
